### ISSUE TITLE
Using Gino with CockroachDB

### ISSUE THREAD

**Issue by snguyenthanh** [python-gino/gino#663]
* GINO version: 1.0.0
* Python version: 3.7.4
* asyncpg version: 0.20.1
* aiocontextvars version: 0.2.2
* CockroachDB version: 19.2.6

### Description

I'm using `Gino` as a PostgreSQL driver for `CockroachDB`. It works well for `GET` queries but fail for `INSERT`. According to the [docs](https://python-gino.org/docs/en/master/tutorials/tutorial.html#create), calling the function `<model>.create()` will execute a SQL query of `INSERT INTO ... `. However, it seems some other SQL queries are also executed. A `PostgreSQL` query seems to not be supported in `CockroachDB` yet, raising an error.

May I ask how I could resolve this ?

### What I Did

On creating a new row, there is an error raised regarding a non-implemented feature of `CockroachDB` in `asyncpg`:

```
INFO:     INSERT INTO image (id, s3_bucket, s3_key, formats, sizes, created_at) VALUES ($1, $2, $3, $4, $5, $6) RETURNING image.id, image.s3_bucket, image.s3_key, image.formats, image.sizes, image.created_at
INFO:     ('2941f3a0-e2ea-4d9d-8e23-2ce7b793bcac', 'testbucket', 'iqEb1mDimiUpRsmG', ['jpeg'], [], 1588471074)
INFO:     COMMIT
ERROR:    Exception in ASGI application
Traceback (most recent call last):
...
    created_obj = await cls(**kwargs).create()
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/gino/crud.py", line 485, in _create
    row = await bind.first(q)
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/gino/engine.py", line 748, in first
    return await conn.first(clause, *multiparams, **params)
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/gino/engine.py", line 328, in first
    return await result.execute(one=True)
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/gino/dialects/base.py", line 215, in execute
    context.statement, context.timeout, args, 1 if one else 0
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/gino/dialects/asyncpg.py", line 184, in async_execute
    result, stmt = await getattr(conn, "_do_execute")(query, executor, timeout)
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/asyncpg/connection.py", line 1423, in _do_execute
    stmt = await self._get_statement(query, None)
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/asyncpg/connection.py", line 338, in _get_statement
    types_with_missing_codecs, timeout)
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/asyncpg/connection.py", line 378, in _introspect_types
    self._intro_query, (list(typeoids),), 0, timeout)
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/asyncpg/connection.py", line 1411, in __execute
    return await self._do_execute(query, executor, timeout)
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/asyncpg/connection.py", line 1423, in _do_execute
    stmt = await self._get_statement(query, None)
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/asyncpg/connection.py", line 328, in _get_statement
    statement = await self._protocol.prepare(stmt_name, query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 163, in prepare
asyncpg.exceptions.FeatureNotSupportedError: at or near "select": syntax error: unimplemented: this syntax
DETAIL:  source SQL:
WITH RECURSIVE typeinfo_tree(
    oid, ns, name, kind, basetype, has_bin_io, elemtype, elemdelim,
    range_subtype, elem_has_bin_io, attrtypoids, attrnames, depth)
AS (
    SELECT
        ti.oid, ti.ns, ti.name, ti.kind, ti.basetype, ti.has_bin_io,
        ti.elemtype, ti.elemdelim, ti.range_subtype, ti.elem_has_bin_io,
        ti.attrtypoids, ti.attrnames, 0
    FROM
            (
        SELECT
            t.oid                           AS oid,
            ns.nspname                      AS ns,
            t.typname                       AS name,
            t.typtype                       AS kind,
            (CASE WHEN t.typtype = 'd' THEN
                (WITH RECURSIVE typebases(oid, depth) AS (
                    SELECT
                        t2.typbasetype      AS oid,
                        0                   AS depth
                    FROM
                        pg_type t2
                    WHERE
                        t2.oid = t.oid

                    UNION ALL

                    SELECT
                        t2.typbasetype      AS oid,
                        tb.depth + 1        AS depth
                    FROM
                        pg_type t2,
                        typebases tb
                    WHERE
                       tb.oid = t2.oid
                       AND t2.typbasetype != 0
               ) SELECT oid FROM typebases ORDER BY depth DESC LIMIT 1)
                 ^
HINT:  You have attempted to use a feature that is not yet implemented.
See: https://github.com/cockroachdb/cockroach/issues/21085
```

**Comment by fantix** [comment]
The extra query is an introspection executed by asyncpg when it didn't get enough knowledge about the types in the query:
 * https://github.com/MagicStack/asyncpg/blob/v0.20.1/asyncpg/introspection.py#L99-L134
 * https://github.com/MagicStack/asyncpg/blob/v0.20.1/asyncpg/connection.py#L328-L338

Though this is not a GINO issue, from your log I suspect that the types of `formats` and `sizes` may have caused the problem.

**Comment by snguyenthanh** [comment]
Thank you very much for the inspection.
You are right that the issue was caused by `ARRAY` type. I think I should change to another driver for CockroachDB if I want to have `ARRAY` columns.

Moreover, just for your information, it seems having multiple active portals (for transactions) is not supported as well.

```
# My code
async with db.transaction():
            result = await func(*args, **kwargs)
```

Exception raised:
```
INFO:     INSERT INTO image (id, s3_bucket, s3_key, extension, created_at) VALUES ($1, $2, $3, $4, $5) RETURNING image.id, image.s3_bucket, image.s3_key, image.extension, image.created_at
INFO:     ('14202a20-4f7b-4871-9cfb-9e88e69ef793', 'testbucket', 'a9k3vq4ei1mx6le2', 'jpeg', 1588575071)
INFO:     COMMIT
ERROR:    Resetting connection with an active transaction <asyncpg.connection.Connection object at 0x11ee0d2f0>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
...
    result = await func(*args, **kwargs)
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/gino/engine.py", line 173, in __aexit__
    return await tx.__aexit__(*exc_info)
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/gino/transaction.py", line 179, in __aexit__
    await self._tx.commit()
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/gino/dialects/asyncpg.py", line 361, in commit
    await self._tx.commit()
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/asyncpg/transaction.py", line 211, in commit
    await self.__commit()
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/asyncpg/transaction.py", line 179, in __commit
    await self._connection.execute(query)
  File "/Users/son/Library/Caches/pypoetry/virtualenvs/project-rain-7LNSaARJ-py3.7/lib/python3.7/site-packages/asyncpg/connection.py", line 272, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 316, in query
asyncpg.exceptions.FeatureNotSupportedError: unimplemented: multiple active portals not supported
HINT:  You have attempted to use a feature that is not yet implemented.
See: https://github.com/cockroachdb/cockroach/issues/40195
```

**Comment by fantix** [comment]
Thanks for sharing! Please also feel free to file a new issue/feature request on https://github.com/MagicStack/asyncpg
